name: Send data to Security Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  send-alerts:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
      - name: Send data to Security Alerts
        uses: heroku/security-alerts-action@stable
        with:
          gh-app-id: ${{ secrets.SECURITY_ALERTS_GH_APP_ID }}
          gh-app-privkey: ${{ secrets.SECURITY_ALERTS_GH_APP_PRIVKEY }}
          webhook-url: ${{ secrets.SECURITY_ALERTS_WEBHOOK_URL }}
          sa-token: ${{ secrets.SECURITY_ALERTS_TOKEN }}
